### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by XiaoLiuAI** [zhangkaixu/isan#1]
你好，我尝试在我的mac上面编译你的程序，但是出现了名字空间问题（我猜的）。

首先，我修改了Makefile，加上了mac下python库的路径选项。然后我将common文件夹下所有的

``` C++
#include <Python.h></code>
```

改成了

``` C++
#ifdef __APPLE__
#include <Python/Python.h>
#else
#include <Python.h>
#endif
```

以确保编译器能找到头文件（在这之前编译器直接报告找不到Python.h）。

之后编译器报错：
common/python_interface.cc:153:27: error: variable 'isan::PyModuleDef isan::module_struct' has initializer but incomplete type
 static struct PyModuleDef module_struct = {

**Comment by zhangkaixu** [comment]
谢谢你的关注！：）
不过我也不清楚怎么回事，我是在Ubuntu的Python3下可以编译。

**Comment by getengqing** [comment]
你好，这个wget http://www.sighan.org/bakeoff2005/data/icwb2-data.rar还能下载吗？好像网页是错的！

**Comment by zhangkaixu** [comment]
@getengqing 似乎已经不行了，可以试试直接搜索sighan bakeoff 2005的语料
